### ISSUE TITLE
Update todo

### ISSUE THREAD

**Issue by andyblarblar** [andyblarblar/queue_alert#16]
- [x] Migrate react to 18
- [x] Migrate Rust to Actix 4
- [x] Refactor timer in server to use tokio directly
- [x] Test aesgcm and see if it fixes firefox
- [x] Send full config to server instead of just park, and only send parks to client when we know at least one ride will trigger
- [x] Bump versions in config and on site
- [x] Update about page

**Comment by andyblarblar** [comment]
Just need to bump versions
